version: '3.8'

services:
  web:
    container_name: bakeneko-test
    build:
      dockerfile: tests/Dockerfile
    volumes:
      - ./:/code
    command: pytest --cov-report html --cov=bakeneko tests/ --html=report.html --self-contained-html
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
  postgres_data: