name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_WEB_HOOK_NAME: ${{ secrets.TG_WEB_HOOK_NAME }}
        CASERVER: ${{ secrets.CASERVER}}
        BAKENEKO_HOST: ${{ secrets.BAKENEKO_HOST }}
        GIT_BRANCH: ${{ secrets.GIT_BRANCH }}
      with:
        envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,POSTGRES_PORT,TG_TOKEN,TG_WEB_HOOK_NAME,CASERVER,BAKENEKO_HOST,GIT_BRANCH
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker compose down -f bakeneko/docker-compose.yml
          rm -rf bakeneko/
          git clone -b $GIT_BRANCH https://github.com/rychanya/bakeneko.git
          echo POSTGRES_USER=$POSTGRES_USER > bakeneko/.env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> bakeneko/.env
          echo POSTGRES_DB=$POSTGRES_DB >> bakeneko/.env
          echo POSTGRES_PORT=$POSTGRES_PORT >> bakeneko/.env
          echo TG_TOKEN=$TG_TOKEN >> bakeneko/.env
          echo TG_WEB_HOOK_NAME=$TG_WEB_HOOK_NAME >> bakeneko/.env
          echo CASERVER=$CASERVER >> bakeneko/.env
          echo BAKENEKO_HOST=$BAKENEKO_HOST >> bakeneko/.env
          cd bakeneko/
          docker compose up -d --build
